closet_project/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('create_clothe', views.create_clothe, name='create_clothe'),
    path('list_clothe', views.list_clothe, name='list_clothe'),
    path('detail_clothe/<int:pk>/', views.detail_clothe, name='detail_clothe'),
    path('edit_clothe/<int:pk>/', views.edit_clothe, name='edit_clothe'),
    path('delete_clothe/<int:pk>/', views.delete_clothe, name='delete_clothe'),
    path('delete_clothe_complete/', views.delete_clothe_complete, name='delete_clothe_complete'),
]

closet_project/closet_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

closet_project/boards/models.py
from django.db import models
from accounts.models import Users

# Create your models here.
class Categories(models.Model):
    
    BLOUSE = 'blouse'
    SHIRT = 'shirt'
    SWEAT = 'sweat'
    KNIT = 'knit'
    PANTS = 'pants'
    SKIRT = 'skirt'
    JACKET = 'jacket'
    CARDIGAN = 'cardigan'
    COAT = 'coat'
    DRESS = 'dress'
    SHOES = 'shoes'
    ACCESSORY = 'accessory'
    BAG = 'bag'
    
    category_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'categories'
        
    def __str__(self):
        return self.category_name
        
        
# class Stores(models.Model):
   
#     store_name = models.CharField(max_length=100)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
    
#     class Meta:
#         db_table = 'stores'

class Colors(models.Model):
    
    PINK = 'pink'
    RED = 'red'
    ORANGE = 'orange'
    BROWN = 'brown'
    YELLOW = 'yellow'
    BLUE = 'blue'
    GREEN = 'green'
    BLACK = 'black'    
    WHITE = 'white'
        
    color_name = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.color_name
    
    class Meta:
        db_table = 'colors'
    
class ClothesManager(models.Manager):
    def fetch_all_clothe(self):
        return self.all()


class Clothes(models.Model):
    
    title = models.CharField(max_length=255)
    picture = models.ImageField(upload_to='closet_project/media/', null=True, blank=True)
    price = models.IntegerField(default=0, null=True, blank=True)
    purchase_date = models.DateField(null=True,blank=True)
    user = models.ForeignKey(
        'accounts.Users', on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        'Categories', on_delete=models.CASCADE
    )
    color = models.ManyToManyField(
        Colors, blank=True, through='Clothe_Colors', related_name='clothe'
    )
    store = models.CharField(max_length=255, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    objects = ClothesManager()
    
    class Meta:
        db_table = 'clothes'
        
    def __str__(self):
        return self.title
    
class Clothe_Colors(models.Model):
    clothe = models.ForeignKey(
        Clothes, on_delete=models.CASCADE, related_name='clothe_color_relation',
    )
    color = models.ForeignKey(
        Colors, on_delete=models.CASCADE, related_name='color_clothe_relation',
    )

closet_project/boards/forms.py
from django import forms
from .models import Categories,  Colors, Clothes 

    
class CreateClotheForm(forms.ModelForm):
    title = forms.CharField(label='商品名', required=True)
    picture = forms.ImageField(label='写真', required=True)
    price = forms.IntegerField(label='価格',required=False)
    purchase_date = forms.DateField(label='購入日', required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    category = forms.ModelChoiceField(label='カテゴリー', 
        queryset=Categories.objects.all(),
        required=True,
    )
    color = forms.ModelMultipleChoiceField(label='カラー', 
        queryset=Colors.objects.all(), 
        widget=forms.CheckboxSelectMultiple,
        required=True,
    )
    store = forms.CharField(label='店名', required=False)
        
    def __init__(self, *args, **kwargs):
       
        categories = kwargs.pop('categories', None)
        colors = kwargs.pop('colors', None)
        instance = kwargs.get('instance')
        super(CreateClotheForm, self).__init__(*args, **kwargs)

        if categories:
            self.fields['category'].queryset = categories

        if colors:
            self.fields['color'].queryset = colors
            
        existing_colors = instance.color.values_list('id', flat=True) if instance and instance.color.exists() else []
        self.initial['color'] = existing_colors
                
                    
    class Meta:
        model=Clothes
        fields = ('title', 'picture', 'price', 'purchase_date', 'category', 'color', 'store')
        widgets = {
        'title': forms.TextInput(attrs={'required': True}),
        'category': forms.Select(attrs={'required': True}),
        'color': forms.CheckboxSelectMultiple(attrs={'required': True}),
        'purchase_date': forms.DateInput(attrs={'type': 'date', 'required': True}),
    }
        error_messages = {
            'title': {
                'required': 'タイトルを入力してください。',
            },
            'picture': {
                'required': '写真を選択してください。',
            },
            'category': {
                'required': 'カテゴリーを選択してください。',
            },
            'color': {
                'required': 'カラーを選択してください。',
            },
        }
        
# class ClotheSearchForm(forms.Form):
#     title = forms.CharField(label='商品名', required=True)
#     store = forms.CharField(label='店名', required=False)
        
class DeleteClotheForm(forms.ModelForm):
    pk = forms.IntegerField(widget=forms.HiddenInput())
    
    class Meta:
        model = Clothes
        fields = []

closet_project/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.contrib import messages
from .models import Categories, Clothes, Colors, Clothe_Colors
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from PIL import Image
import os

# Create your views here.    

@login_required
def create_clothe(request):
    categories = Categories.objects.all() 
    colors = Colors.objects.all()
    if request.method =='POST':
        create_clothe_form = forms.CreateClotheForm(request.POST, request.FILES)
        if create_clothe_form.is_valid():
            title = create_clothe_form.cleaned_data['title']
            picture = create_clothe_form.cleaned_data['picture']
            price = create_clothe_form.cleaned_data['price']
            purchase_date = create_clothe_form.cleaned_data['purchase_date']
            store_name = create_clothe_form.cleaned_data['store']
            category_name = create_clothe_form.cleaned_data['category']
            selected_colors = create_clothe_form.cleaned_data['color']
            
            category_instance = Categories.objects.filter(category_name=category_name).first()
            color_instance_list = [] 
            for color_id in selected_colors:
                color_instance = color_id
                if color_instance:
                    color_instance_list.append(color_instance)
            
            new_clothe = create_clothe_form.save(commit=False)
            new_clothe.user = request.user
            
            # if 'picture' in request.FILES:
            #     print(request.FILES['picture'])
            #     image = Image.open(request.FILES['picture'])
            #     desired_width = 300
            #     desired_height = 200
            #     resized_image = image.resize((desired_width, desired_height))
        

                # new_clothe.picture = request.FILES['picture']
                # print(new_clothe.picture.url)
                           
            if category_instance:
                new_clothe.category = category_instance
                
            new_clothe.save()

            for color_instance in color_instance_list:
                Clothe_Colors.objects.create(clothe=new_clothe, color=color_instance)
            
            return redirect('boards:list_clothe') 
         
        else:
            # フォームがバリデーションエラーだった場合の処理
            print(create_clothe_form.errors) 
           
            
    else:
        create_clothe_form = forms.CreateClotheForm()
        
    return render(
        request, 'boards/create_clothe_form.html', context={
            'create_clothe_form': create_clothe_form,
            'categories': categories, 
            'colors': colors,
        }
    )

@login_required    
def list_clothe(request):
    sort_option = request.GET.get('sort', '')  # URL パラメーターからソートオプションを取得
    
    color = Colors.objects.all()
    category = Categories.objects.all()

    selected_color = request.GET.get('color')
    selected_category = request.GET.get('category')
    # search_query = request.GET.get('search') 
    search_title = request.GET.get('search_title')
    search_store = request.GET.get('search_store')
    
    clothe = Clothes.objects.filter(user=request.user)
    
    if selected_color:
        clothe = clothe.filter(color__color_name=selected_color)

    if selected_category:
        clothe = clothe.filter(category__category_name=selected_category)
    
    # if search_query:
    #     clothe = clothe.filter(
    #         Q(title__icontains=search_query) |
    #         Q(store__icontains=search_query) 
    #     )
    
    if search_title:
        clothe = clothe.filter(title__icontains=search_title)

    if search_store:
        clothe = clothe.filter(store__icontains=search_store)
                
    if sort_option == 'price_low':
        clothe = clothe.order_by('price')
    elif sort_option == 'price_high':
        clothe = clothe.order_by('-price')
    elif sort_option == 'date_new':
        clothe = clothe.order_by('-purchase_date')
    elif sort_option == 'date_old':
        clothe = clothe.order_by('purchase_date')
    
    return render(
        request, 'boards/list_clothe.html', context={
            'clothe': clothe,
            'color': color,
            'category': category,
            'selected_color': selected_color,
            'selected_category': selected_category,
            # 'search_query': search_query,
            'search_title': search_title,
            'search_store': search_store,
        }
    )

@login_required
def detail_clothe(request, pk):
    clothe = get_object_or_404(Clothes, pk=pk)
    print(f"Color: {clothe.color.all()}")  # デバッグ用のログ出力
    return render(
        request, 'boards/detail_clothe.html', context={
            'clothe': clothe,
        }
    )
    
@login_required
def edit_clothe(request, pk):
    categories = Categories.objects.all()
    colors = Colors.objects.all()
    
    clothe=get_object_or_404(Clothes, pk=pk)
    
    if clothe.user.pk != request.user.pk:
        raise Http404
    
    if request.method == 'POST':
        print('POST request received')
        edit_clothe_form = forms.CreateClotheForm(request.POST or None, request.FILES or None, instance=clothe)
        if edit_clothe_form.is_valid():
            edit_clothe_form.save()
            return redirect(
                'boards:detail_clothe', 
                pk=pk
            ) 
    else:
        edit_clothe_form = forms.CreateClotheForm(instance=clothe)
            
    return render(
        request, 'boards/edit_clothe.html', context={
            'edit_clothe_form':edit_clothe_form,
            'pk': pk,
            'categories': categories,
            'colors': colors,
        }
    )

@login_required
def delete_clothe(request, pk):
    deleted_clothe = get_object_or_404(Clothes, pk=pk)
    if request.method == 'POST':
        deleted_clothe.delete()  # 服を削除
        return redirect('boards:delete_clothe_complete')
    
    return render(
        request, 'boards/delete_clothe.html', context={
            'clothe': deleted_clothe
        }
    )

  
def delete_clothe_complete(request):
    return redirect('boards:list_clothe')  

closet_project/templates/boards/create_clothe_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <p class="custom-paragraph">服登録画面</p>
  <div class="registration-container">
    <form method="POST" enctype="multipart/form-data"  class="registration-form">
      {% csrf_token %}

      <div class="form-group">
        <label for="title">商品名  <span style="color: red; font-size: 85%;">必須</span></label>
        <input type="text" id="title" name="title" class="form-control" required>
      </div>

      {% if new_clothe.picture %}
         <div class="image-container">
           <img src="{{ new_clothe.picture.url }}" alt="{{ new_clothe.title }}" class="clothe-image">
        </div>
      {% endif %}
      <div class="form-group">
        <label for="image">写真  <span style="color: red; font-size: 85%;">必須</span></label>
        <input type="file" id="image" name="picture" accept="image/*" class="form-control" onchange="previewImage()">
      </div>
      
      <div id="image-preview-container"></div>
      <div class="form-group">
        <label for="price">価格</label>
        <input type="number" id="price" name="price" class="form-control">
      </div>
      <div class="form-group">
        <label for="purchase_date">購入日</label>
        <input type="date" id="purchase_date" name="purchase_date" class="form-control">
      </div>
      <div class="form-group">
        <label for="store">店名</label>
        <input type="text" id="store" name="store" class="form-control">
      </div>
      <div class="form-group">
        <label for="category">カテゴリー  <span style="color: red; font-size: 85%;">必須</span></label>
        <select id="category" name="category" class="form-control" required>
          {% for category in categories %}
            <option value="{{ category.id }}">{{ category.category_name }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label>カラー  <span style="color: red; font-size: 85%;">必須</span></label>
        {% for color in colors %}
          <div class="form-check">
            <input type="checkbox" id="color_{{ color.id }}" name="color" value="{{ color.id }}" class="form-check-input">
            <label for="color_{{ color.id }}" class="form-check-label">{{ color.color_name }}</label>
          </div>
        {% endfor %}
      </div>  
      <div class="button-container">
        <button type="submit" class="btn btn-primary">登録</button>
      </div>
    </form>
  </div>
<script src="{% static 'js/image_preview.js' %}"></script>
{% endblock %}

closet_project/templates/boards/delete_clothe.html
{% extends "base.html" %}
{% block content %}
    <h3>削除確認</h3>
    <p>本当にこの服を削除しますか？</p>
    <p>タイトル: {{ clothe.title }}</p>
    {% if clothe.picture %}
        <p>画像: <img src="{{ clothe.picture.url }}" alt="{{ clothe.title }}" width="100"></p>
    {% else %}
        <p>画像: </p>
    {% endif %}
    <p>価格: {{ clothe.price|default_if_none:"" }}</p>
    <p>購入日: {{ clothe.purchase_date|date:"Y年m月d日"|default_if_none:"" }}</p>
    <p>カテゴリー: {{ clothe.category }}</p>
    <p>カラー:
        {% for color in clothe.color.all %}
            {{ color.color_name }}
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>   
    <p>購入したお店: {{ clothe.store }}</p>
    <form id="delete-form" method="POST" action="{% url 'boards:delete_clothe' pk=clothe.pk %}">
      {% csrf_token %}
      
      <a href="{% url 'boards:detail_clothe' pk=clothe.pk %}">キャンセル</a>
     
      <input id="delete-button" type="submit" value="はい、削除します">
    </form>
    <script>
      document.getElementById("delete-form").addEventListener("submit", function(event) {
      event.preventDefault();
      this.submit();  
      });
    </script>
{% endblock %}

closet_project/templates/boards/delete_clothe_complete.html
{% extends "base.html" %}
{% block content %}
 <h3>服の削除が完了しました。</h3>
{% endblock %}

closet_project/templates/boards/detail_clothe.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p class="custom-paragraph">服詳細画面</p> 
<div class="detail-container">
  <div class="detail-left">
    {% if clothe.picture %}
        <p><img src="{{ clothe.picture.url }}" alt="{{ clothe.title }}" class="image-custom"></p>
    {% else %}
        <p class="no-image">画像なし</p>
    {% endif %}
  </div>
   <div class="detail-right">
    <p class="title">{{ clothe.title }}</p>
    
    <div class="detail-info">
      <div class="info-row">
        <p class="info-label">価格:</p>
        <p class="info-value"> {{ "￥"|default_if_none:"" }}{{ clothe.price|default_if_none:"" }}</p>
      </div>
      
      <div class="info-row">
        <p class="info-label">購入日:</p>
        <p class="info-value"> {{ clothe.purchase_date|date:"Y年m月d日"|default_if_none:"未登録" }}</p>
      </div>
      
      <div class="info-row">
        <p class="info-label">店名:</p>
        <p class="info-value"> {{ clothe.store|default_if_none:"   " }}</p>
      </div>
      
      <div class="info-row">
        <p class="info-label">カテゴリー:</p>
        <p class="info-value"> {{ clothe.category|default_if_none:"   " }}</p>
      </div>
      
      <div class="info-row">
        <p class="info-label">カラー:</p>
        <span class="info-value">
        {% for color_instance in clothe.color.all %}
            {{ color_instance.color_name }}
            {% if not forloop.last %}、{% endif %}
        {% endfor %}
    </span>
    </div>
  </div>
    <div class="button-container">
      <a href="{% url 'boards:edit_clothe' pk=clothe.pk %}">
        <button type="submit" class="btn btn-primary">編集</button>
      </a>
        <button type="button" class="btn btn-danger" onclick="confirmDelete()" style="margin-left: 30px;">削除</button>
      <form id="delete-form-temp" method="POST" action="{% url 'boards:delete_clothe' pk=clothe.pk %}">
        {% csrf_token %}
      </form>
    </div>
    <script>
    function confirmDelete() {
      console.log('confirmDelete called');
      var deleteForm = document.getElementById('delete-form-temp');
      if (deleteForm) {
        console.log('deleteForm found');
        if (confirm('本当に削除しますか？')) {
          console.log('Confirmed, submitting form');
          deleteForm.submit();
        } else {
          console.log('Not confirmed, form not submitted');
        }
      } else {
        console.log('deleteForm not found');
      }
    }
  </script>
  <script src="{% static 'js/image_preview.js' %}"></script> 
  </div>
</div>

{% endblock %}

closet_project/templates/boards/edit_clothe.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <p class="custom-paragraph">服編集画面</p> 
  <div class="registration-container">
    <form method="POST" enctype="multipart/form-data" class="registration-form">
      {% csrf_token %}
      {{ edit_clothe.as_p }}
      <div class="form-group">
        <label for="title">商品名<span style="color: red; font-size: 85%;">  必須</span></label>
        <input type="text" id="title" name="title" class="form-control" required value="{{ edit_clothe_form.instance.title }}">
      </div>
      
      <div class="form-group">
        <label for="image">写真<span style="color: red; font-size: 85%;">  必須</span></label>
        <div id="image-preview-container"></div>
        <input type="file" id="image" name="picture" accept="image/*" class="form-control" onchange="previewImage()">
      </div>
      {% if edit_clothe_form.instance.picture %}
         <div class="image-container">
           <img src="{{ edit_clothe_form.instance.picture.url }}" alt="{{ edit_clothe_form.instance.title }}" class="clothe-image">
        </div>
      {% endif %}
      <div class="form-group">
        <label for="price">価格</label>
        <input type="number" id="price" name="price" class="form-control" value="{{ edit_clothe_form.instance.price }}">
      </div>
      <div class="form-group">
        <label for="purchase_date">購入日</label>
        <input type="date" id="purchase_date" name="purchase_date" class="form-control" value="{{ edit_clothe_form.instance.purchase_date|date:'Y-m-d' }}">
      </div>
      <div class="form-group">
        <label for="store">店名</label>
        <input type="text" id="store" name="store" class="form-control" value="{{ edit_clothe_form.instance.store }}">
      </div>
      <div class="form-group">
        <label for="category">カテゴリー<span style="color: red; font-size: 85%;">  必須</span></label>
        <select id="category" name="category" class="form-control" required value="{{ edit_clothe_form.instance.category.id }}">
          {% for category in categories %}
            <option value="{{ category.id }}" {% if category.id == edit_clothe_form.instance.category.id %}selected{% endif %}>{{ category.category_name }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label>カラー<span style="color: red; font-size: 85%;">  必須</span></label>
        {% for color in colors %}
          <div class="form-check">
              <input type="checkbox" id="color_{{ color.id }}" name="color" value="{{ color.id }}" class="form-check-input" {% if color.id in edit_clothe_form.initial.color %}checked{% endif %}>
              <label for="color_{{ color.id }}" class="form-check-label">{{ color.color_name }}</label>
          </div>
        {% endfor %}
      </div>
      <div class="button-container">
        <button type="submit" class="btn btn-primary">更新</button>
        <button type="button" class="btn btn-danger" onclick="confirmDelete()" style="margin-left: 30px;">削除</button>
      </div>
    </form>

    <form id="delete-form-temp" method="POST" action="{% url 'boards:delete_clothe' pk=edit_clothe_form.instance.pk %}">
      {% csrf_token %}
   
    </form>
  </div>
  <script>
    function confirmDelete() {
      console.log('confirmDelete called');
      var deleteForm = document.getElementById('delete-form-temp');
      if (deleteForm) {
        console.log('deleteForm found');
        if (confirm('本当に削除しますか？')) {
          console.log('Confirmed, submitting form');
          deleteForm.submit();
        } else {
          console.log('Not confirmed, form not submitted');
        }
      } else {
        console.log('deleteForm not found');
      }
    }
  </script>
  <script src="{% static 'js/image_preview.js' %}"></script>
{% endblock %}

closet_project/templates/boards/list_clothe.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
  {% for message in messages %}
  <div>{{ message.message }}</div>
  {% endfor %}
{% endif %}
<p class="custom-paragraph">服一覧画面</p>   
<div class="row justify-content-center">
  <div class="col-md-8">

  <form id="searchForm" method="GET" class="text-center mb-3 form-element">
    <input type="text" name="search_title" id="search_title" placeholder="商品名検索">
    <button type="submit" class="btn custom-btn"><i class="fas fa-search"></i></button>
  </form>

  <form id="searchStoreForm" method="GET" class="text-center mb-3 form-element">
    <input type="text" name="search_store" id="search_store" placeholder="店名検索">
    <button type="submit" class="btn custom-btn"><i class="fas fa-search"></i></button>
  </form>

  <form id="resetForm" method="GET" class="text-center mb-3 form-element">
  <button type="button" onclick="resetFilters()" class="btn custom-btn">リセット</button>
  </form>

  <style>
#resetForm button {
  padding: 8px 50px; 
  margin-right: 50px;
}
</style>

  <script>
function resetFilters() {
  // カラーとカテゴリーのセレクトボックスをリセット
  document.getElementById("color").value = "";
  document.getElementById("category").value = "";

  // フォームを送信する
  document.getElementById("filterForm").submit();
}
</script>



  <style>
  #sortForm {
    margin-right: 100px;
  }
  </style>

  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <form id="sortForm" method="GET" class="text-center mb-3 form-element">
    <select name="sort" id="sort" onchange="submitSortForm()">
      <option value="">並び替え</option>
      <option value="price_low">価格が安い順</option>
      <option value="price_high">価格が高い順</option>
      <option value="date_new">購入日が新しい順</option>
      <option value="date_old">購入日が古い順</option>
    </select>
  </form> 

<script>
  function submitSortForm() {
    var sortValue = $("#sort").val();

    // カスタムの並び替えロジック
    if (sortValue === "price_low" || sortValue === "date_old") {
      // 価格が記載されているアイテムが上に来るように調整
      $(".item").sort(function(a, b) {
        var aValue = sortValue === "price_low" ? ($(a).data("price") !== undefined ? parseFloat($(a).data("price")) : -Infinity) : $(a).data("date");
        var bValue = sortValue === "price_low" ? ($(b).data("price") !== undefined ? parseFloat($(b).data("price")) : -Infinity) : $(b).data("date");

        // 実際の並び替えロジック
        return bValue - aValue; // bからaに変更して逆順に
      }).appendTo(".items-container");
    }

    // フォームの送信または他のアクションを実行する（必要に応じて）
    $("#sortForm").submit();
  }
</script>

  <form id="filterForm" method="GET" class="text-center mb-3 form-element">
    <select name="color" id="color">
        <option value="">全ての色</option>
        {% for c in color %}
            <option value="{{ c.color_name }}" {% if c.color_name == selected_color %}selected{% endif %}>{{ c.color_name }}</option>
        {% endfor %}
    </select>    
    <select name="category" id="category" >
        <option value="">全てのカテゴリー</option>
        {% for cat in category %}
            <option value="{{ cat.category_name }}" {% if cat.category_name == selected_category %}selected{% endif %}>{{ cat.category_name }}</option>
        {% endfor %}
      <input type="submit" value="絞り込み" class="btn custom-btn">
    </select>
  </form>
  </div>
</div>
   <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th></th>
        <th>商品名</th>
        <th>写真</th>
        <th>価格</th>
        <th>購入日</th>
        <th>カテゴリー</th>
        <th>カラー</th>
        <th>店名</th>
      </tr>
    </thead>
    <tbody>
    {% for clothe in clothe %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'boards:detail_clothe' pk=clothe.pk %}">{{ clothe.title }}</a></td>
        <td>
          {% if clothe.picture %}
          <img src="{{ clothe.picture.url }}" alt="{{ clothe.title }}" width="100">
          {% endif %}
        </td>
        <td>{{ "￥"|default_if_none:"" }}{{ clothe.price|default_if_none:"" }}</td>
        <td>{{ clothe.purchase_date|date:"Y年m月d日"|default_if_none:"" }}</td>
        <td>{{ clothe.category.category_name }}</td>
        <td>
          {% for color in clothe.color.all %}
            {{ color.color_name }}
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </td>
        <td>{{ clothe.store }}</td>
      </tr>
        {% endfor %}
    </tbody>
  </table>
  <script>
  document.addEventListener('DOMContentLoaded', function () {
    // ページ読み込み時に選択されたオプションがあれば選択状態にする
    var selectedOption = document.getElementById("sort").value;
    if (selectedOption) {
      document.getElementById("sort").value = selectedOption;
    }
  });

  function submitSortForm() {
    var selectedOption = document.getElementById("sort").value;
    if (selectedOption) {
     
      document.getElementById("sortForm").submit();
    }
   
    return false;
  }
</script>
{% endblock %}