closet_project/accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import CustomLoginView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.portfolio, name='portfolio'),
    path('home', views.home, name='home'),
    path('admin/', admin.site.urls),  # admin画面のURL設定
    path('regist', views.regist, name='regist'),
    path('activate_user/<uuid:token>', views.activate_user, name='activate_user'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('user_edit', views.user_edit, name='user_edit'),
    path('change_password', views.change_password, name='change_password'),
]

closet_project/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('create_clothe', views.create_clothe, name='create_clothe'),
    path('list_clothe', views.list_clothe, name='list_clothe'),
    path('detail_clothe/<int:pk>/', views.detail_clothe, name='detail_clothe'),
    path('edit_clothe/<int:pk>/', views.edit_clothe, name='edit_clothe'),
    path('delete_clothe/<int:pk>/', views.delete_clothe, name='delete_clothe'),
    path('delete_clothe_complete/', views.delete_clothe_complete, name='delete_clothe_complete'),
]

closet_project/closet_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

closet_project/accounts/models.py
from django.db import models
from django.contrib.auth.models import(
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.db.models.signals import post_save
from django.dispatch import receiver
from uuid import uuid4
from django.utils import timezone
from django.utils.timezone import timedelta

from django.urls import reverse_lazy
from django.contrib import admin

        
class UserManager(BaseUserManager):
        
    def _create_user(self, username, email, password):
        if not email:
            raise ValueError('Enter Email')
        user = self.model(
            username=username,
            email=email,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, username, email, password=None, **extra_fields):
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password=None):
        if password is None:
            raise ValueError('Superuser must have a password')

        user = self._create_user(username, email, password)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
    
class Users(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    objects = UserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    class Meta:
        db_table = 'users'

class UserActivateTokensManager(models.Manager):    
   
    def activate_user_by_token(self, token):
        user_activate_token = UserActivateTokens.objects.filter(
            token=token,
            expired_at__gte=timezone.now()
        ).first()
        if user_activate_token:
            user = user_activate_token.user
            user.is_active = True
            user.save()
            return user
        return None
        
class UserActivateTokens(models.Model):
    
    token = models.UUIDField(db_index=True)
    expired_at =models.DateTimeField()
    user = models.ForeignKey(
        'Users', on_delete=models.CASCADE
    )
    
    objects = UserActivateTokensManager()
    
    class Meta:
        db_table = 'user_activate_tokens'
          
   
        
@receiver(post_save, sender=Users)
def publish_token(sender, instance, **kwargs):
    print("Post save signal called")
    user_activate_token = UserActivateTokens.objects.create(
        user=instance, token=str(uuid4()), expired_at=timezone.now() + timedelta(days=1)
    )
    print(f"Token: {user_activate_token.token}, Expired At: {user_activate_token.expired_at}")

closet_project/accounts/forms.py
from django import forms
from .models import Users, UserManager
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password


class RegistForm(forms.ModelForm):
    username = forms.CharField(label='ユーザ名', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='メールアドレス', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta():
        model = Users
        fields = ('username', 'email', 'password')
        
    def clean_username(self):
        value = self.cleaned_data['username']
        if len(value) < 3:
            raise forms.ValidationError(
                '%(min_length)s文字以上で入力してください', params={'min_length': 3})
        return value

    def clean_email(self):
        value = self.cleaned_data['email']
        return value

    def clean_password(self):
        value = self.cleaned_data['password']
        return value
                
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password !=confirm_password:
            raise forms.ValidationError('パスワードが異なります')
        
    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user
    
class LoginForm(forms.Form):
    email = forms.EmailField(label="メールアドレス")
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput())
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise ValidationError("メールアドレスを入力してください。")
        return email
    
class UserEditForm(forms.ModelForm):
    username = forms.CharField(label='ユーザ名')
    email = forms.EmailField(label='メールアドレス')
        
    class Meta:
        model = Users
        fields = ('username', 'email')
        
class PasswordChangeForm(forms.Form):
    
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())
        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password !=confirm_password:
            raise forms.ValidationError('パスワードが異なります')
        
    def save(self, user, commit=True):
        password = self.cleaned_data["password"]
        user.set_password(password)  # パスワードのハッシュ化
        if commit:
            user.save()
        return user

closet_project/accounts/views.py
from django.shortcuts import render, redirect
from . import forms
from django.core.exceptions import ValidationError
from .models import UserActivateTokens
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.views import LoginView
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.models import UserManager
from django.contrib.auth import password_validation

User = get_user_model()

def portfolio(request):
    return render(
        request, 'accounts/portfolio.html'
    )

def home(request):
    return render(
        request, 'accounts/home.html'
    )
    
def regist(request):
    regist_form = forms.RegistForm(request.POST or None)
    if regist_form.is_valid():
        try:
            user = regist_form.save(commit=False)
            user.is_active = True  # アカウントを有効にする
            user.save()
            return redirect('accounts:user_login')
        except ValidationError as e:
            regist_form.add_error('password', e) 
    return render(
        request, 'accounts/regist.html', context={
            'regist_form': regist_form,
        }
    )
    
def activate_user(request, token):
    user_activate_token = UserActivateTokens.objects.activate_user_by_token(token)
    if user_activate_token:
        return HttpResponse("ユーザーをアクティブ化しました。")
    else:
        return HttpResponse("トークンが無効です。")
    
    return render(request, 'accounts/activate_user.html')
    
def user_login(request):
    login_form = forms.LoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        
        if user:
            if user.is_active:
                login(request, user)
                if user.is_staff:  
                    return redirect('admin:index')
                else:
                    return redirect('accounts:home')
            else:
                raise ValidationError('ユーザがアクティブではありません')
        else:
            messages.warning(request, 'メールかパスワードが間違っています')
    return render(
        request, 'accounts/user_login.html', context={
            'login_form': login_form,
        }
    )
    

    
@login_required
def user_logout(request):
    logout(request)
    return redirect('accounts:home')

@login_required
def user_edit(request):
    user_edit_form = forms.UserEditForm(request.POST or None, request.FILES or None, instance=request.user)
    if user_edit_form.is_valid():
        user_edit_form.save()
    return render(request, 'accounts/user_edit.html', context={
        'user_edit_form': user_edit_form,
    })
    
@login_required
def change_password(request):
    if request.method == 'POST':
        password_change_form = forms.PasswordChangeForm(data=request.POST)
        if password_change_form.is_valid():
            password = password_change_form.cleaned_data['password']
            confirm_password = password_change_form.cleaned_data['confirm_password']

            if password != confirm_password:
                messages.error(request, 'パスワードが一致しません。')
            else:
                user = request.user
                user.set_password(password)
                user.save()
                update_session_auth_hash(request, user)
                return redirect('accounts:home')
    else:
        password_change_form = forms.PasswordChangeForm()

    return render(
        request, 'accounts/change_password.html', context={
            'password_change_form': password_change_form
        }
    )
    

class CustomLoginView(LoginView):
    template_name = 'accounts/user_login.html'

    def get_success_url(self):
        user = self.request.user

        if user.is_staff:
            # 管理者ユーザーの場合は管理者サイトへ遷移
            return reverse('admin:index')
        elif user.is_active:
            # activeなユーザーの場合はHOME画面へ遷移
            return reverse('accounts:home')
        else:
            # 上記の条件に合致しない場合、デフォルトの遷移先になります
            return super().get_success_url()

closet_project/templates/accounts/activate_user.html
{% extends "base.html" %}
{% block content %}
ユーザを有効化しました
{% endblock %}

closet_project/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
<div class="text-center">
{% if messages %}
  {% for message in messages %}
    <div>{{ message }}</div>
  {% endfor %}
{% endif %}
<form method="POST">
{% csrf_token %}
{{ password_change_form.as_p }}
<div class="button-container">
 <button type="submit" class="btn btn-primary">パスワード更新</button>
</div>
</form>
</div>
{% endblock %}

closet_project/templates/accounts/home.html
{% extends "base.html" %}

{% block content %}
  {% load static %}
  {% if messages %}
    {% for message in messages %}
      <div>{{ message.message }}</div>
    {% endfor %}
  {% endif %}

  <p class="custom-paragraph">welcome to my closet</p>

  <h1 class="heading1">あなただけの closet へようこそ</h1>
  <h1 class="heading1">いつでも どこにいても お気に入りの一着を</h1>

  <div class="image-container">
  <img src="{% static 'accounts/images/clothes.jpg' %}" class="custom-image">
  </div>

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

closet_project/templates/accounts/portfolio.html
<!DOCTYPE html>
{% block content %}
  {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
</head>
<body>
    <h1 class="heading2">作品No.1 my closet</h1>

    <div class="image-container">
    <img src="{% static 'accounts/images/portfolio.jpg' %}" class="custom-image">
    </div>

    <h1 class="heading1">「いつもとは違う色の服を買いたい！」「持っている服と合わせたいな」と思ったことはありませんか？</h1>
    <h1 class="heading1">my closetは、そんな願いを叶えられるアプリです</h1>
    <h1 class="heading1">自分の服を管理して</h1>
    <h1 class="heading1">いつでも、どこへでも自分の服を持ち運ぼう！</h1>
    <!-- ポートフォリオからアプリへのリンク -->
    <button type="button" onclick="window.location.href='{% url 'accounts:home' %}'" class="btn custom-btn">アプリにアクセス</button>

  
</body>
</html>

<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

closet_project/templates/accounts/regist.html
{% extends "base.html" %}
{% block content %}
  <p class="custom-paragraph">ユーザ登録画面</p>
   <div class="registration-container">
    <form method="POST" enctype="multipart/form-data"  class="registration-form">
      {% csrf_token %}

      <div class="form-group">
        <label>ユーザ名 </label>
        {{ regist_form.username}}
        {{ regist_form.username.errors }}
        <p>3文字以上で設定してください</p>
      </div>

       <div class="form-group">
        <label for="email">メールアドレス</label>
        {{ regist_form.email}}
        {{ regist_form.email.errors }}
      </div>

      <div class="form-group">
        <label for="password">パスワード</label>
        {{ regist_form.password}}
        {{ regist_form.password.errors }}
        <p>英字を含めた8文字以上で設定してください</p>
      </div>

      <div class="form-group">
        <label for="confirm_password">パスワード再入力</label>
        {{ regist_form.confirm_password}}
        {{ regist_form.confirm_password.errors }}
      </div>

      <div class="button-container">
        <button type="submit" class="btn btn-primary">ユーザ登録</button>
      </div>
    </form>
   </div>
{% endblock %}

closet_project/templates/accounts/user_edit.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
  {% for message in messages %}
    <div>{{ message.message }}</div>
  {% endfor %}
{% endif %}
<div class="text-center">
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ user_edit_form.as_p }}
<div class="button-container">
      <button type="submit" class="btn btn-primary">更新</button>
    </div>
</form>
<p></p>
<a href="{% url 'accounts:change_password' %}">パスワード変更</a>
</div>
{% endblock %}

closet_project/templates/accounts/user_login.html
{% extends "base.html" %}
{% block content %}

<div class="text-center">
  <form method="POST">
   {% csrf_token %}
   {{ login_form.as_p }}
   {% if messages %}
  {% for message in messages %}
    <div style="color: red;">{{ message.message }}</div>
  {% endfor %}
{% endif %}
   <div class="button-container">
      <button type="submit" class="btn btn-primary">ログイン</button>
    </div>
  </form>
</div>
{% endblock %}